Add \ in front of _ in file names inside latex color blocks
Latex was throwing a misleading error when it found
underscores in a file name inside a color block.
Here is the misleading error:
! Missing $ inserted.
<inserted text>
                $
l.2145 ...nto a reinstated Error Models section.}}

Try to find the following text in p9_v01_all_combined____APP__supplemental_information.Rmd:
  ...nto a reinstated Error Models section.}}

You may need to add $ $ around a certain inline R expression `r ` in p9_v01_all_combined____APP__supplemental_information.Rmd (see the above hint). See https://github.com/rstudio/rmarkdown/issues/385 for more info.
Error: LaTeX failed to compile p9_v01_all_combined____APP__supplemental_information.tex. See https://yihui.org/tinytex/r/#debugging for debugging tips. See p9_v01_all_combined____APP__supplemental_information.log for more info.
Execution halted